### ISSUE TITLE
EDIT: TypeError: subcon should be a Construct field

### ISSUE THREAD

**Issue by minecraft2048** [daniestevez/gr-satellites#16]
I've installed gr-satellites with this command:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr  .. 
make -j8 
sudo make install
```
as I'm on Arch Linux and the AUR packager for Gnuradio and other gr-* blocks installed it there. Then, when I try to start any of the example flowcharts, this happens:

Executing: /usr/sbin/python2 -u /home/feanor/Development/SDR/gr-satellites/apps/au02.py

Traceback (most recent call last):
  File "/home/feanor/Development/SDR/gr-satellites/apps/au02.py", line 23, in <module>
    from sync_to_pdu_packed import sync_to_pdu_packed  # grc-generated hier_block
  File "/home/feanor/.grc_gnuradio/sync_to_pdu_packed.py", line 15, in <module>
    import satellites
ImportError: No module named satellites

What kind of `satellites` module should I expect?

EDIT: I've retried running `sudo make install`, then when I try to import `satellites` into python2 , this happens:
```
feanor@silmaril ~> python2
Python 2.7.15 (default, May  1 2018, 20:16:04) 
[GCC 7.3.1 20180406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import satellites
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/satellites/__init__.py", line 86, in <module>
    from snet_deframer import snet_deframer
  File "/usr/lib/python2.7/site-packages/satellites/snet_deframer.py", line 27, in <module>
    from snet_telemetry import LTUFrameHeader
  File "/usr/lib/python2.7/site-packages/satellites/snet_telemetry.py", line 59, in <module>
    Const(BitsInteger(18), 0b111100110101000000),
  File "/usr/lib/python2.7/site-packages/construct/core.py", line 2461, in __init__
    super(Const, self).__init__(subcon)
  File "/usr/lib/python2.7/site-packages/construct/core.py", line 562, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
>>> 
```
EDIT 2: Turns out construct changed their API and it breaks a lot of pythons everywhere, so using this workaround: https://github.com/home-assistant/home-assistant/issues/11768#issuecomment-358764563

```
feanor@silmaril ~> sudo pip2 install construct==2.8.21
```
it works now

**Comment by daniestevez** [comment]
Thanks for the report. It is difficult to support both construct-2.8 and construct-2.9 since there are many API changes between both versions. However, I try to support both, so this should be fixed in 31a1e34bd87e1e83b55ee7f1559741fd197773bd (meaning that you should be able to use construct-2.9 as well).
