### ISSUE TITLE
build-ubuntu CI pipeline is failing

### ISSUE THREAD

**Issue by daniestevez** [daniestevez/gr-satellites#303]
We're getting errors like these in the tests:

```
1: Test command: /usr/bin/sh "/github/workspace/build/python/qa_fixedlen_tagger_test.sh"
1: Test timeout computed to be: 10000000
1: Traceback (most recent call last):
1:   File "/github/workspace/python/qa_fixedlen_tagger.py", line 24, in <module>
1:     from satellites import fixedlen_tagger
1: ModuleNotFoundError: No module named 'satellites'
 1/14 Test  #1: qa_fixedlen_tagger ...............***Failed    0.22 sec
```

I think this is caused by the release of Ubuntu 21.10, since we're using `ubuntu:latest` as base Docker image.

**Comment by daniestevez** [comment]
It appears that there's a problem with the GNU Radio 3.9.3.0 PPA package. Using the PPA package I get this problem. If instead I build GNU RAdio 3.9.3.0 from source, it works.

To use the PPA package I'm using this Dockerfile:
```
# syntax=docker/dockerfile:1
FROM ubuntu:latest
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y software-properties-common \
    && add-apt-repository ppa:gnuradio/gnuradio-releases \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y upgrade \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
           gnuradio build-essential cmake git swig liborc-0.4-dev \
	   python3-pip \
    && pip3 install construct \
    && git clone https://github.com/daniestevez/gr-satellites \
    && cd gr-satellites \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && ldconfig
ENV PYTHONPATH /usr/local/lib/python3/dist-packages/
```

If I run `python3 -c "import satellites; print(satellites.__version__)"` using that image I get
```
Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/satellites/__init__.py", line 42, in <module>
    from .bindings.satellites_python import *
ModuleNotFoundError: No module named 'satellites.bindings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3/dist-packages/satellites/__init__.py", line 44, in <module>
    from .satellites_python import *
ImportError: generic_type: type "ax100_decode" referenced unknown base type "gr::block"
```

To build GNU Radio (and Volk) from source I'm using this Dockerfile:
```
# syntax=docker/dockerfile:1
FROM ubuntu:latest
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y software-properties-common \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y upgrade \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
           build-essential cmake git \
	   python3-pip \
	   g++ libboost-all-dev libgmp-dev swig python3-numpy \
	   python3-mako python3-sphinx python3-lxml doxygen libfftw3-dev \
	   libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev python3-pyqt5 \
	   liblog4cpp5-dev libzmq3-dev python3-yaml python3-click python3-click-plugins \
	   python3-zmq python3-scipy python3-gi python3-gi-cairo gir1.2-gtk-3.0 \
	   libcodec2-dev libgsm1-dev \
	   pybind11-dev python3-matplotlib libsndfile1-dev \
    && pip3 install construct \
    && git clone --recursive https://github.com/gnuradio/volk \
    && cd volk \
    && git checkout v2.5.0 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && git clone https://github.com/gnuradio/gnuradio \
    && cd gnuradio \
    && git checkout v3.9.3.0 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && git clone https://github.com/daniestevez/gr-satellites \
    && cd gr-satellites \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && ldconfig
ENV PYTHONPATH /usr/local/lib/python3/dist-packages/
```

If I run `python3 -c "import satellites; print(satellites.__version__)"` using this image I get
```
v4.4.0-git
```
as expected.
