### ISSUE TITLE
Readthedocs build fails

### ISSUE THREAD

**Issue by daniestevez** [daniestevez/gr-satellites#316]
Since a week ago, the readthedocs builds are failing with this error:
```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 14 source files that are out of date
updating environment: 14 added, 0 changed, 0 removed
reading sources... [  7%] command_line
reading sources... [ 14%] components
reading sources... [ 21%] index
reading sources... [ 28%] installation
reading sources... [ 35%] installation_conda
reading sources... [ 42%] installation_intro
reading sources... [ 50%] installation_ppa
reading sources... [ 57%] introduction
reading sources... [ 64%] low_level
reading sources... [ 71%] overview
reading sources... [ 78%] satellite_decoder
reading sources... [ 85%] satyaml
reading sources... [ 92%] supported_satellites
/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/checkouts/latest/docs/source/command_line.rst:516: WARNING: Error in "code-block" directive:
1 argument(s) required, 0 supplied.

.. code-block::

    [Groundstation]
    callsign =
    latitude = 0
    longitude = 0
    submit_tlm = no

    [FUNcube]
    site_id =
    auth_code =
    [PW-Sat2]
    credentials_file =

    [BME]
    user =
    password =

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 245, in apply
    apply_source_workaround(n)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/gr-satellites/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible

The full traceback has been saved in /tmp/sphinx-err-4b2qbvyt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

I don't know yet the cause of this problem, but I think that nothing that could cause this has changed in the documentation.

The first build that started failing was 9e8629aeac54b036ef45fa8ad19e94ac98266a1d, while b689462bd8f321b1572fd465c72f20dbcaa2e8a5 built correctly.

**Comment by daniestevez** [comment]
I have just check and the problem has been fixed without doing anything on my end.
