### ISSUE TITLE
Persisting installation problems

### ISSUE THREAD

**Issue by stefanpi1** [daniestevez/gr-satellites#364]
Hi Daniel,
I'm suffering from persisting problems with my installation, so I need to bother you once more.

After everything worked perfectly for a few observations, something unknown happened and gr_satellite fails to start in the pre-observation  with the following error:

Traceback (most recent call last):
  File "/usr/local/bin/gr_satellites", line 16, in <module>
    import satellites.core
  File "/usr/local/lib/python3/dist-packages/satellites/__init__.py", line 49, in <module>
    from .adsb_kml import adsb_kml
  File "/usr/local/lib/python3/dist-packages/satellites/adsb_kml.py", line 15, in <module>
    from .telemetry import gomx_3 as tlm
  File "/usr/local/lib/python3/dist-packages/satellites/telemetry/__init__.py", line 30, in <module>
    from .cute_70cm import cute_70cm
  File "/usr/local/lib/python3/dist-packages/satellites/telemetry/cute_70cm.py", line 86, in <module>
    class FswParserState(Enum):
TypeError: function() argument 1 must be code, not str

PYTHONPATH is set globaly in /etc/profile and gr_satellite works from the commandline.
Since i could not find the reason for the problem and I have messed around too much, looking for a solution, I decided to make a new clean install from an empty sd-card.

Out of a sudden, now its wants to have gr 3.10 now and stops the build-process - dont know why?

pi@raspberrypi:~/gr-satellites/build $ cmake ..
-- Build type not specified: defaulting to release.
CMake Error at CMakeLists.txt:97 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.10".

  The following configuration files were considered but not accepted:

    /usr/lib/arm-linux-gnueabihf/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.2.0
    /lib/arm-linux-gnueabihf/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.2.0

-- Configuring incomplete, errors occurred!
See also "/home/pi/gr-satellites/build/CMakeFiles/CMakeOutput.log".
pi@raspberrypi:~/gr-satellites/build $

Any ideas, how i can get one of these two setups working?

Thank you in advance for your help

Stefan/OE6ISP

**Comment by stefanpi1** [comment]
Thanks a lot for your quick reply!! Using the correct branch solved the problem on the new build - works perfectly now!
(So no need to analyze, whats wrong with the goofed environment of the old setup)
