### ISSUE TITLE
Missing deviation and af_carrier in most AFSK satellites

### ISSUE THREAD

**Issue by daniestevez** [daniestevez/gr-satellites#99]
I have noticed that most SatYAML files for AFSK satellites do not have `deviation` and `af_carrier` parameters. Probably this gives problems.

**Comment by daniestevez** [comment]
In fact there is no way this could work. For example:

```
$ gr_satellites BRICSat-2 --udp --samp_rate 48e3
Traceback (most recent call last):
  File "/usr/local/bin/gr_satellites", line 170, in <module>
    main()
  File "/usr/local/bin/gr_satellites", line 156, in main
    tb = gr_satellites_top_block(parser)
  File "/usr/local/bin/gr_satellites", line 86, in __init__
    self.flowgraph = satellites.core.gr_satellites_flowgraph(samp_rate = options.samp_rate, iq = self.options.iq,
  File "/usr/local/lib/python3/dist-packages/satellites/core/gr_satellites_flowgraph.py", line 146, in __init__
    demodulator = self.get_demodulator(transmitter['modulation'])(baudrate = baudrate, samp_rate = samp_rate, iq = iq, dump_path = dump_path, options = options, **demodulator_additional_options)
TypeError: __init__() missing 2 required positional arguments: 'af_carrier' and 'deviation'
```
